import { createContext, useContext, useState, type ReactNode } from 'react';

type Language = 'en' | 'hi' | 'pa' | 'mr' | 'ta' | 'te' | 'bn';

type Translations = {
    [key in Language]: {
        [key: string]: string;
    };
};

const translations: Translations = {
    en: {
        "dashboard_title_official": "Official Dashboard",
        "dashboard_title_worker": "Worker Dashboard",
        "welcome_back": "Welcome back",
        "what_happening": "Here's what's happening with your account today.",
        "reports": "Reports",

        "team_attendance": "Team Attendance",
        "attendance_overview": "Attendance Overview",
        "view_report": "View Report",
        "quick_actions": "Quick Actions",
        "approve_leave": "Approve Leave",
        "transfers": "Transfers",
        "mcd_portal": "MCD Portal",
        "official_portal": "MCD Official Portal",
        "management_mode": "Management Mode",
        "live_location": "Live Location",
        "dept_grievances": "Dept. Grievances",
        "dept_leaves": "Dept. Leaves",
        "administration": "Administration",
        "overview": "Overview",
        "requests": "Requests",
        "overall": "Overall",
        "department": "Department",
        "attendance_analytics": "Attendance Analytics",
        "payroll_center": "Payroll Command Center",
        "leave_management": "Leave Management",
        "grievance_management": "Grievance Management",
        "official_list": "Official List",
        "announce": "Announce",
        "mark_in": "Mark In (Face)",
        "setup_face": "Setup Face ID",
        "apply_leave": "Apply Leave",
        "payslip": "Payslip",
        "form_16": "Form 16",
        "recent_transfers": "Recent Transfer Requests",
        "recent_payroll": "Recent Payroll",
        "view_all": "View All History",
        "active_grievances": "Active Grievances",
        "view_all_tickets": "View All Tickets",
        "logout": "Log Out",
        "need_help": "Need Help?",
        "contact_support": "Contact support for payroll issues.",
        "nav_dashboard": "Dashboard",
        "nav_attendance": "Attendance",
        "nav_payroll": "Payroll",
        "nav_transfers": "Transfers",
        "nav_grievances": "Grievances",
        "nav_profile": "Profile",
        "wip": "Work in Progress",
        "grievance_submitted": "Grievance submitted successfully!",
        "grievance_title": "Title",
        "grievance_desc": "Description",
        "submit": "Submit",
        "cancel": "Cancel",
        "submit_grievance_modal_title": "Submit a Grievance",
        "days_present": "Days Present",
        "leave_balance": "Leave Balance",
        "next_pay_date": "Next Pay Date",
        "pending_actions": "Pending Actions",
        "total_workers": "Total Workers",
        "dept_attendance": "Dept. Attendance",
        "pending_grievances": "Pending Grievances",
        "total_payroll": "Total Payroll",
        "post_notice": "Post Notice",
        "add_user": "Add User",
        "my_profile": "My Profile",
        "dept_management": "Dept. Management",
        "admin_console": "Admin Console",
        "department_specific": "Department Specific Controls",
        "central_hub": "Central Administration Hub",
        "expires_dec": "Expires Dec 31",
        "processing": "Payroll processing...",
        "view_details": "View details",
        "active_in_dept": "Active in Dept",
        "daily_attendance": "Daily Attendance",
        "verify_attendance_desc": "Verify your location and scan your face to mark your presence for the day.",
        "mark_attendance": "Mark Attendance",
        "view_records": "View Records",
        "attendance_history": "Attendance History",
        "location_verification": "Location Verification",
        "live_camera": "Live Camera Feed",
        "employee_details": "Employee Details",
        "face_scan": "Face Scan",
        "location_check": "Location Check",
        "confirmation": "Confirmation",
        "setup_face_now": "Setup Face ID Now",
        "payroll_management": "Payroll Management",
        "my_payslip": "My Payslip",
        "payroll_desc_hr": "Manage employee salaries and view reports",
        "payroll_desc_user": "View and download your salary slips",
        "process_new_payroll": "Process New Payroll",
        "total_disbursed": "Total Disbursed (All Time)",
        "employees_paid": "Employees Paid",
        "recent_transactions": "Recent Transactions",
        "active_employees": "Active Employees",
        "net_pay": "Net Pay",
        "earnings": "Earnings",
        "deductions": "Deductions",
        "download_pdf": "Download PDF",
        "payment_history": "Payment History",
        "create_payroll": "Create Payroll",
        "save_payroll": "Save Payroll",
        "basic_col": "Basic",
        "hra_col": "HRA",
        "conveyance_col": "Conveyance",
        "medical_col": "Medical",
        "special_col": "Special",
        "pf_col": "PF",
        "esi_col": "ESI",
        "tax_col": "Tax",
        "total": "Total",
        "status": "Status",
        "action": "Action",
        "month": "Month",
        "paid_on": "Paid On",
        "my_grievances": "My Grievances",
        "grievances_desc": "Manage and track your reported issues",
        "submit_grievance": "Submit Grievance",
        "my_submitted_grievances": "My Submitted Grievances",
        "no_grievances": "No grievances submitted.",
        "topic": "Topic",
        "view": "View",
        "submitted_on": "Submitted on",
        "description": "Description",
        "discussion": "Discussion",
        "type_reply": "Type a reply...",
        "grievance_closed": "This grievance is closed",
        "no_replies": "No replies yet.",
        "voice_grievance": "Voice Grievance",
        "new_voice_submission": "New Voice Submission",
        "voice_grievance_submission": "Voice Grievance Submission",
        "voice_grievance_desc": "Press the microphone button and speak clearly to record your complaint. You can select your preferred language below.",
        "browser_verified": "Browser Verified",
        "browser_not_supported": "Speech Recognition is not supported in this browser. Please use Google Chrome, Microsoft Edge, or Safari.",
        "select_language": "Select Language",
        "audio_waveform": "Audio waveform will appear here",
        "polishing_ai": "Polishing your text with AI...",
        "mic_unavailable": "Microphone unavailable",
        "tap_stop": "Tap stop to finish recording",
        "tap_mic": "Tap microphone to start recording",
        "preview": "Preview",
        "clear": "Clear",
        "additional_details": "Additional Details",
        "brief_title": "Brief title",
        "recipient": "Recipient",
        "ai_selected": "AI Selected",
        "analyzing": "Analyzing...",
        "official": "Official",
        "my_department": "My Department",
        "hr_dept": "HR Dept",
        "general_admin": "General/Admin",
        "additional_notes": "Additional Notes",
        "type_extra_info": "Type any extra information here if you couldn't say it...",
        "recording_tips": "Recording Tips",
        "tip_quiet": "Find a quiet place to record.",
        "tip_clear": "Speak clearly and at a normal pace.",
        "tip_time": "Max recording time is 2 minutes.",
        "tip_phone": "Keep the phone close if using mobile.",
        "sending": "Sending...",

        "user_management": "User Management",
        "register_employee": "Register New Employee",
        "register_desc": "Enter details to auto-generate User ID & Password. Credentials will be emailed.",
        "generating_creds": "Generating credentials and sending email...",
        "error_creating": "Error creating user",
        "email_sent": "Email Sent",
        "user_id": "User ID",
        "password": "Password",
        "personal_details": "Personal Details",
        "full_name": "Full Name (as per ID)",
        "dob": "Date of Birth",
        "aadhar": "Aadhar Card No.",
        "contact_job": "Contact & Job",
        "email_address": "Email Address",
        "phone_number": "Phone Number",
        "designation": "Post / Designation",
        "designation_placeholder": "e.g. Sanitation Worker I",
        "role": "Role",
        "worker": "Worker",
        "hr_admin": "HR / Admin",
        "generate_email": "Generate & Email Credentials",
        "hr_restricted": "HR (Restricted)",
        "dept_education": "Education",
        "dept_health": "Health",
        "dept_engineering": "Engineering",
        "dept_sanitation": "Sanitation",
        "dept_general": "General",

        "service_request": "Service Request",
        "id_card_generator": "ID Card Generator",
        "dept_document_nav": "Dept. Document",
        "department_suffix": "Department",
        "doc_type_transfer_order": "Transfer Order",
        "doc_type_general": "General",
        "doc_type_official": "Official",

        "grievance_hub": "Grievance Hub",
        "grievance_hub_desc": "Review and resolve issues",
        "filter_all": "All",
        "filter_officials": "Officials",
        "filter_workers": "Workers",
        "grievance_resolved": "RESOLVED",
        "grievance_pending": "PENDING",
        "grievance_active_count": "Active",

        "management_actions": "Management Actions",
        "team_reports_label": "Team Reports",
        "department_notices": "Department Notices",
        "manage_notices": "Manage Notices",
        "notices_posted_text": "You have posted {count} notices this month.",

        "secure_login": "Secure Login",
        "help_support": "Help / Support",
        "unified_sys": "Unified Management System",
        "streamlined_access": "Streamlined access for all Municipal Corporation users. Manage attendance, payroll, transfers, and grievances in one secure location.",
        "employee_services_title": "Employee Services",
        "employee_services_desc": "Access payroll slips and leave records instantly.",
        "attendance_tracking_title": "Attendance Tracking",
        "attendance_tracking_desc": "Real-time biometric and geo-tagged attendance logs.",
        "grievance_redressal_title": "Grievance Redressal",
        "grievance_redressal_desc": "Direct channel for internal complaints and resolution.",
        "copyright": "© 2026 Municipal Corporation. All rights reserved.",
        "sign_in_title": "Sign in to your account",
        "enter_creds": "Please enter your credentials to access the dashboard.",
        "forgot_password": "Forgot Password?",
        "demo_login": "Demo Login (HR Admin)",
        "no_account": "Don't have an account?",
        "contact_dept_head": "Contact your Department Head.",
        "privacy_policy": "Privacy Policy",
        "terms_service": "Terms of Service",
        "security_guidelines": "Security Guidelines",

        "choose_language_title": "Choose Language / भाषा चुनें",
        "select_lang_desc": "Select your preferred language for the portal.",
        "register_face_id": "Register your face ID for secure attendance.",
        "start_camera": "Start Camera",
        "loading_models": "Loading AI Models...",
        "face_captured": "Face Captured!",
        "confirm_enrollment": "Confirm Enrollment",
        "registering": "Registering...",
        "retake": "Retake",
        "all_set": "All Set!",
        "face_registered_msg": "Your face ID has been registered.",
        "next": "Next",
        "finish_setup": "Finish Setup",
        "face_enrolled_success": "Face enrolled successfully!",
        "no_face_detected": "No face detected to enroll. Please retry capture.",
        "camera_error": "Failed to access camera",

        "access_denied": "Access Denied",
        "tracking_presence": "Tracking monthly presence for",
        "search_employee": "Search employee...",
        "loading_attendance": "Loading attendance data...",
        "present_days": "Present",
        "absent_off": "Absent/Off",
        "total_days": "Total Days",
        "no_records": "No records found.",
        "dept_documents": "Department Documents",
        "dept_docs_desc": "Access and manage all official documents for your department.",
        "total_docs": "Total Documents",
        "doc_name": "Document Name",
        "doc_date": "Date",
        "doc_type": "Type",
        "doc_actions": "Actions",
        "print_doc": "Print Document",
        "view_doc": "View Document",
        "viewing_doc": "You are viewing",
        "doc_placeholder": "This is a placeholder for the actual document viewer.",
        "print": "Print",
        "download": "Download",
        "dept_grievances_desc": "Review and resolve grievances from your department",
        "resolve_fail": "Failed to resolve grievance.",
        "reply_fail": "Failed to send reply",
        "dept_workforce": "Department Workforce",
        "managing_workers": "Managing workers in",
        "search_workers": "Search workers...",
        "loading_workforce": "Loading workforce data...",
        "employee_header": "Employee",
        "post_designation": "Post/Designation",
        "contact_header": "Contact",
        "status_header": "Status",
        "face_reg": "Face Reg",
        "pending_face": "Pending Face",
        "onboarded": "Onboarded",
        "new_status": "New",
        "viewing_records": "Viewing records for ID:",
        "recent_activity": "Recent Activity",
        "detailed_records": "Detailed Records",
        "time_header": "Time",
        "location_header": "Location",
        "attendance_analytics_hub": "Attendance Analytics Hub",
        "real_time_presence": "Real-time presence across departments",
        "payroll_command_center": "Payroll Command Center",
        "cycle_txt": "Cycle",
        "cycle_completed": "CYCLE COMPLETED",
        "action_required_caps": "ACTION REQUIRED",
        "total_allocated": "Total Allocated",
        "actual_disbursal": "Actual Disbursal",
        "release_batch_payout": "Release Batch Payout",
        "payouts_released": "Payouts Released",
        "budget_status": "Budget Status",
        "active_grievances_label": "Active Grievances",
        "present_days_chart": "Present Days",
        "tab_overview": "Overview",
        "tab_payroll": "Payroll",
        "tab_grievances": "Grievances",
        "tab_leaves": "Leaves",
        "tab_livemap": "Live Map",
        "status_processing": "Processing",
        "status_pending": "Pending",
        "status_released": "Released",
        "legend_present": "Present",
        "legend_absent": "Absent",
        "legend_on_leave": "On Leave",
    },
    hi: {
        "dashboard_title_official": "अधिकारी डैशबोर्ड",
        "dashboard_title_worker": "कर्मी डैशबोर्ड",
        "welcome_back": "वापसी पर स्वागत है",
        "what_happening": "आज आपके खाते में क्या हो रहा है, यहां देखें।",
        "reports": "रिपोर्ट्स",

        "team_attendance": "टीम उपस्थिति",
        "attendance_overview": "उपस्थिति अवलोकन",
        "view_report": "रिपोर्ट देखें",
        "quick_actions": "त्वरित कार्रवाई",
        "approve_leave": "छुट्टी मंजूर करें",
        "transfers": "स्थानांतरण",
        "mcd_portal": "एमसीडी पोर्टल",
        "official_portal": "एमसीडी आधिकारिक पोर्टल",
        "management_mode": "प्रबंधन मोड",
        "live_location": "लाइव लोकेशन",
        "dept_grievances": "विभाग शिकायतें",
        "dept_leaves": "विभाग छुट्टियाँ",
        "administration": "प्रशासन",
        "overview": "अवलोकन",
        "requests": "अनुरोध",
        "overall": "समग्र",
        "department": "विभाग",
        "attendance_analytics": "उपस्थिति विश्लेषण",
        "payroll_center": "वेतन कमांड सेंटर",
        "leave_management": "छुट्टी प्रबंधन",
        "grievance_management": "शिकायत प्रबंधन",
        "official_list": "अधिकारी सूची",
        "announce": "घोषणा करें",
        "mark_in": "हाजिरी लगाएं (चेहरा)",
        "setup_face": "फेस आईडी सेट करें",
        "apply_leave": "छुट्टी के लिए आवेदन",
        "payslip": "वेतन पर्ची",
        "form_16": "फॉर्म 16",
        "recent_transfers": "हालिया स्थानांतरण अनुरोध",
        "recent_payroll": "हालिया वेतन",
        "view_all": "सभी इतिहास देखें",
        "active_grievances": "सक्रिय शिकायतें",
        "view_all_tickets": "सभी टिकट देखें",
        "logout": "लॉग आउट",
        "need_help": "मदद चाहिए?",
        "contact_support": "पेरोल समस्याओं के लिए संपर्क करें।",
        "nav_dashboard": "डैशबोर्ड",
        "nav_attendance": "उपस्थिति",
        "nav_payroll": "वेतन",
        "nav_transfers": "स्थानांतरण",
        "nav_grievances": "शिकायतें",
        "nav_profile": "प्रोफ़ाइल",
        "wip": "कार्य प्रगति पर है",
        "grievance_submitted": "शिकायत सफलतापूर्वक दर्ज की गई!",
        "grievance_title": "शीर्षक",
        "grievance_desc": "विवरण",
        "submit": "जमा करें",
        "cancel": "रद्द करें",
        "submit_grievance_modal_title": "शिकायत दर्ज करें",
        "days_present": "उपस्थित दिन",
        "leave_balance": "छुट्टी शेष",
        "next_pay_date": "अगली वेतन तिथि",
        "pending_actions": "लंबित कार्य",
        "total_workers": "कुल कर्मचारी",
        "dept_attendance": "विभाग उपस्थिति",
        "pending_grievances": "लंबित शिकायतें",
        "total_payroll": "कुल वेतन",
        "post_notice": "नोटिस जारी करें",
        "add_user": "उपयोगकर्ता जोड़ें",
        "my_profile": "मेरी प्रोफ़ाइल",
        "dept_management": "विभाग प्रबंधन",
        "admin_console": "प्रशासन कंसोल",
        "department_specific": "विभाग विशिष्ट नियंत्रण",
        "central_hub": "केंद्रीय प्रशासन हब",
        "expires_dec": "31 दिसंबर को समाप्त",
        "processing": "वेतन संसाधित हो रहा है...",
        "view_details": "विवरण देखें",
        "active_in_dept": "विभाग में सक्रिय",
        "daily_attendance": "दैनिक उपस्थिति",
        "verify_attendance_desc": "दिन के लिए अपनी उपस्थिति दर्ज करने के लिए अपना स्थान सत्यापित करें और चेहरे को स्कैन करें।",
        "mark_attendance": "उपस्थिति दर्ज करें",
        "view_records": "रिकॉर्ड देखें",
        "attendance_history": "उपस्थिति इतिहास",
        "location_verification": "स्थान सत्यापन",
        "live_camera": "लाइव कैमरा फीड",
        "employee_details": "कर्मचारी विवरण",
        "face_scan": "चेहरा स्कैन",
        "location_check": "स्थान जांच",
        "confirmation": "पुष्टिकरण",
        "setup_face_now": "अब फेस आईडी सेट करें",
        "payroll_management": "वेतन प्रबंधन",
        "my_payslip": "मेरी पेस्लिप",
        "payroll_desc_hr": "कर्मचारी वेतन प्रबंधित करें और रिपोर्ट देखें",
        "payroll_desc_user": "अपनी वेतन पर्चियां देखें और डाउनलोड करें",
        "process_new_payroll": "नया वेतन प्रोसेस करें",
        "total_disbursed": "कुल वितरित (अब तक)",
        "employees_paid": "भुगतान किए गए कर्मचारी",
        "recent_transactions": "हालिया लेनदेन",
        "active_employees": "सक्रिय कर्मचारी",
        "net_pay": "शुद्ध वेतन",
        "earnings": "आय",
        "deductions": "कटौतियां",
        "download_pdf": "PDF डाउनलोड करें",
        "payment_history": "भुगतान इतिहास",
        "create_payroll": "वेतन बनाएं",
        "save_payroll": "वेतन सहेजें",
        "basic_col": "मूल",
        "hra_col": "एचआरए",
        "conveyance_col": "वाहन भत्ता",
        "medical_col": "चिकित्सा",
        "special_col": "विशेष",
        "pf_col": "पीएफ",
        "esi_col": "ईएसआई",
        "tax_col": "कर",
        "total": "कुल",
        "status": "स्थिति",
        "action": "कार्रवाई",
        "month": "महीना",
        "paid_on": "भुगतान तिथि",
        "my_grievances": "मेरी शिकायतें",
        "grievances_desc": "अपनी रिपोर्ट की गई समस्याओं का प्रबंधन और ट्रैक करें",
        "submit_grievance": "शिकायत जमा करें",
        "my_submitted_grievances": "मेरी जमा की गई शिकायतें",
        "no_grievances": "कोई शिकायत जमा नहीं की गई।",
        "topic": "विषय",
        "view": "देखें",
        "submitted_on": "जमा की गई",
        "description": "विवरण",
        "discussion": "चर्चा",
        "type_reply": "जवाब टाइप करें...",
        "grievance_closed": "यह शिकायत बंद है",
        "no_replies": "अभी तक कोई जवाब नहीं।",
        "voice_grievance": "वॉयस शिकायत",
        "new_voice_submission": "नई वॉयस सबमिशन",
        "voice_grievance_submission": "वॉयस शिकायत जमा करें",
        "voice_grievance_desc": "अपनी शिकायत दर्ज करने के लिए माइक्रोफ़ोन बटन दबाएं और स्पष्ट रूप से बोलें। आप नीचे अपनी पसंदीदा भाषा चुन सकते हैं।",
        "browser_verified": "ब्राउज़र सत्यापित",
        "browser_not_supported": "इस ब्राउज़र में स्पीच रिकग्निशन समर्थित नहीं है। कृपया Google Chrome, Microsoft Edge, या Safari का उपयोग करें।",
        "select_language": "भाषा चुनें",
        "audio_waveform": "ऑडियो वेवफ़ॉर्म यहाँ दिखाई देगा",
        "polishing_ai": "एआई के साथ अपने पाठ को पॉलिश कर रहा है...",
        "mic_unavailable": "माइक्रोफ़ोन अनुपलब्ध",
        "tap_stop": "रिकॉर्डिंग समाप्त करने के लिए स्टॉप टैप करें",
        "tap_mic": "रिकॉर्डिंग शुरू करने के लिए माइक्रोफ़ोन टैप करें",
        "preview": "पूर्वावलोकन",
        "clear": "साफ़ करें",
        "additional_details": "अतिरिक्त विवरण",
        "brief_title": "संक्षिप्त शीर्षक",
        "recipient": "प्राप्तकर्ता",
        "ai_selected": "एआई चयनित",
        "analyzing": "विश्लेषण कर रहा है...",
        "official": "अधिकारी",
        "my_department": "मेरा विभाग",
        "hr_dept": "एचआर विभाग",
        "general_admin": "सामान्य/प्रशासन",
        "additional_notes": "अतिरिक्त नोट्स",
        "type_extra_info": "यदि आप इसे कह नहीं सके तो कोई अतिरिक्त जानकारी यहाँ टाइप करें...",
        "recording_tips": "रिकॉर्डिंग युक्तियाँ",
        "tip_quiet": "रिकॉर्ड करने के लिए एक शांत जगह खोजें।",
        "tip_clear": "स्पष्ट रूप से और सामान्य गति से बोलें।",
        "tip_time": "अधिकतम रिकॉर्डिंग समय 2 मिनट है।",
        "tip_phone": "यदि मोबाइल का उपयोग कर रहे हैं तो फोन को पास रखें।",
        "sending": "भेजा जा रहा है...",

        "user_management": "उपयोगकर्ता प्रबंधन",
        "register_employee": "नया कर्मचारी पंजीकृत करें",
        "register_desc": "यूज़र आईडी और पासवर्ड ऑटो-जेनरेट करने के लिए विवरण दर्ज करें। क्रेडेंशियल्स ईमेल किए जाएंगे।",
        "generating_creds": "क्रेडेंशियल्स जनरेट हो रहे हैं और ईमेल भेजा जा रहा है...",
        "error_creating": "उपयोगकर्ता बनाने में त्रुटि",
        "email_sent": "ईमेल भेजा गया",
        "user_id": "यूज़र आईडी",
        "password": "पासवर्ड",
        "personal_details": "व्यक्तिगत विवरण",
        "full_name": "पूरा नाम (आईडी के अनुसार)",
        "dob": "जन्म तिथि",
        "aadhar": "आधार कार्ड नंबर",
        "contact_job": "संपर्क और नौकरी",
        "email_address": "ईमेल पता",
        "phone_number": "फ़ोन नंबर",
        "designation": "पद / ओहदा",
        "designation_placeholder": "उदा. सफाई कर्मचारी I",
        "role": "भूमिका",
        "worker": "कर्मी",
        "hr_admin": "एचआर / एडमिन",
        "generate_email": "क्रेडेंशियल्स जनरेट और ईमेल करें",
        "hr_restricted": "एचआर (प्रतिबंधित)",
        "dept_education": "शिक्षा",
        "dept_health": "स्वास्थ्य",
        "dept_engineering": "इंजीनियरिंग",
        "dept_sanitation": "स्वच्छता",
        "dept_general": "सामान्य",

        "secure_login": "सुरक्षित लॉगिन",
        "help_support": "सहायता / समर्थन",
        "unified_sys": "एकीकृत प्रबंधन प्रणाली",
        "streamlined_access": "सभी नगर निगम उपयोगकर्ताओं के लिए सुव्यवस्थित पहुंच। उपस्थिति, वेतन, स्थानांतरण और शिकायतों को एक सुरक्षित स्थान पर प्रबंधित करें।",
        "employee_services_title": "कर्मचारी सेवाएं",
        "employee_services_desc": "वेतन पर्ची और छुट्टी रिकॉर्ड तुरंत प्राप्त करें।",
        "attendance_tracking_title": "उपस्थिति ट्रैकिंग",
        "attendance_tracking_desc": "रियल-टाइम बायोमेट्रिक और जियो-टैग उपस्थिति लॉग।",
        "grievance_redressal_title": "शिकायत निवारण",
        "grievance_redressal_desc": "आंतरिक शिकायतों और समाधान के लिए सीधा चैनल।",
        "copyright": "© 2026 नगर निगम। सर्वाधिकार सुरक्षित।",
        "sign_in_title": "अपने खाते में साइन इन करें",
        "enter_creds": "डैशबोर्ड तक पहुंचने के लिए कृपया अपने क्रेडेंशियल्स दर्ज करें।",
        "forgot_password": "पासवर्ड भूल गए?",
        "demo_login": "डेमो लॉगिन (एचआर एडमिन)",
        "no_account": "खाता नहीं है?",
        "contact_dept_head": "अपने विभागाध्यक्ष से संपर्क करें।",
        "privacy_policy": "गोपनीयता नीति",
        "terms_service": "सेवा की शर्तें",
        "security_guidelines": "सुरक्षा दिशानिर्देश",

        "choose_language_title": "भाषा चुनें / Choose Language",
        "select_lang_desc": "पोर्टल के लिए अपनी पसंदीदा भाषा चुनें।",
        "register_face_id": "सुरक्षित उपस्थिति के लिए अपना फेस आईडी पंजीकृत करें।",
        "start_camera": "कैमरा शुरू करें",
        "loading_models": "एआई मॉडल लोड हो रहे हैं...",
        "face_captured": "चेहरा स्कैन किया गया!",
        "confirm_enrollment": "पंजीकरण की पुष्टि करें",
        "registering": "पंजीकरण हो रहा है...",
        "retake": "रीटेक",
        "all_set": "सब तैयार!",
        "face_registered_msg": "आपका फेस आईडी पंजीकृत हो गया है।",
        "next": "अगला",
        "finish_setup": "सेटअप समाप्त करें",
        "face_enrolled_success": "फेस सफलतापूर्वक पंजीकृत किया गया!",
        "no_face_detected": "पंजीकरण के लिए कोई चेहरा नहीं मिला। कृपया पुनः प्रयास करें।",
        "camera_error": "कैमरे तक पहुंचने में विफल",

        "access_denied": "पहुंच अस्वीकृत",
        "tracking_presence": "मासिक उपस्थिति ट्रैकिंग",
        "search_employee": "कर्मचारी खोजें...",
        "loading_attendance": "उपस्थिति डेटा लोड हो रहा है...",
        "present_days": "उपस्थित",
        "absent_off": "अनुपस्थित/अवकाश",
        "total_days": "कुल दिन",
        "no_records": "कोई रिकॉर्ड नहीं मिला।",
        "dept_documents": "विभाग दस्तावेज़",
        "dept_docs_desc": "अपने विभाग के सभी आधिकारिक दस्तावेजों तक पहुंचें और प्रबंधित करें।",
        "total_docs": "कुल दस्तावेज़",
        "doc_name": "दस्तावेज़ का नाम",
        "doc_date": "तारीख",
        "doc_type": "प्रकार",
        "doc_actions": "कार्रवाई",
        "print_doc": "दस्तावेज़ प्रिंट करें",
        "view_doc": "दस्तावेज़ देखें",
        "viewing_doc": "आप देख रहे हैं",
        "doc_placeholder": "यह वास्तविक दस्तावेज़ दर्शक के लिए एक प्लेसहोल्डर है।",
        "print": "प्रिंट",
        "download": "डाउनलोड",
        "dept_grievances_desc": "अपने विभाग की शिकायतों की समीक्षा करें और समाधान करें",
        "resolve_fail": "शिकायत सुलझाने में विफल।",
        "reply_fail": "उत्तर भेजने में विफल",
        "dept_workforce": "विभाग कार्यबल",
        "managing_workers": "कार्यबल प्रबंधन",
        "search_workers": "श्रमिक खोजें...",
        "loading_workforce": "कार्यबल डेटा लोड हो रहा है...",
        "employee_header": "कर्मचारी",
        "post_designation": "पद/ओहदा",
        "contact_header": "संपर्क",
        "status_header": "स्थिति",
        "face_reg": "फेसReg",
        "pending_face": "पेंडिंग फेस",
        "onboarded": "ऑनबोर्डेड",
        "new_status": "नया",
        "viewing_records": "आईडी के रिकॉर्ड देख रहे हैं:",
        "recent_activity": "हाल की गतिविधि",
        "detailed_records": "विस्तृत रिकॉर्ड",
        "time_header": "समय",
        "location_header": "स्थान",
        "attendance_analytics_hub": "उपस्थिति विश्लेषण केंद्र",
        "real_time_presence": "विभागों में रीयल-टाइम उपस्थिति",
        "payroll_command_center": "वेतन आदेश केंद्र",
        "cycle_txt": "चक्र",
        "cycle_completed": "चक्र पूर्ण",
        "action_required_caps": "कार्रवाई आवश्यक",
        "total_allocated": "कुल आवंटित",
        "actual_disbursal": "वास्तविक संवितरण",
        "release_batch_payout": "बैच भुगतान जारी करें",
        "payouts_released": "भुगतान जारी",
        "budget_status": "बजट स्थिति",
        "active_grievances_label": "सक्रिय शिकायतें",
        "present_days_chart": "उपस्थित दिन",
        "tab_overview": "अवलोकन",
        "tab_payroll": "वेतन",
        "tab_grievances": "शिकायतें",
        "tab_leaves": "छुट्टियाँ",
        "tab_livemap": "लाइव मैप",
        "status_processing": "प्रक्रियाधीन",
        "status_pending": "लंबित",
        "status_released": "जारी",
        "legend_present": "उपस्थित",
        "legend_absent": "अनुपस्थित",
        "legend_on_leave": "छुट्टी पर",


        "service_request": "सेवा अनुरोध",
        "id_card_generator": "आईडी कार्ड जेनरेटर",
        "dept_document_nav": "विभाग दस्तावेज़",
        "department_suffix": "विभाग",
        "doc_type_transfer_order": "स्थानांतरण आदेश",
        "doc_type_general": "सामान्य",
        "doc_type_official": "आधिकारिक",

        "grievance_hub": "शिकायत केंद्र",
        "grievance_hub_desc": "शिकायतों की समीक्षा और समाधान करें",
        "filter_all": "सभी",
        "filter_officials": "अधिकारी",
        "filter_workers": "कर्मचारी",
        "grievance_resolved": "हल किया गया",
        "grievance_pending": "लंबित",
        "grievance_active_count": "सक्रिय",

        "management_actions": "प्रबंधन कार्य",
        "team_reports_label": "टीम रिपोर्ट",
        "department_notices": "विभाग नोटिस",
        "manage_notices": "नोटिस प्रबंधित करें",
        "notices_posted_text": "आपने इस महीने {count} नोटिस पोस्ट किए हैं।",
    },
    pa: {
        "dashboard_title_official": "ਅਧਿਕਾਰੀ ਡੈਸ਼ਬੋਰਡ",
        "dashboard_title_worker": "ਵਰਕਰ ਡੈਸ਼ਬੋਰਡ",
        "welcome_back": "ਜੀ ਆਇਆਂ ਨੂੰ",
        "what_happening": "ਇੱਥੇ ਵੇਖੋ ਅੱਜ ਤੁਹਾਡੇ ਖਾਤੇ ਵਿੱਚ ਕੀ ਹੋ ਰਿਹਾ ਹੈ।",
        "reports": "ਰਿਪੋਰਟਾਂ",

        "team_attendance": "ਟੀਮ ਹਾਜ਼ਰੀ",
        "attendance_overview": "ਹਾਜ਼ਰੀ ਝਲਕ",
        "view_report": "ਰਿਪੋਰਟ ਵੇਖੋ",
        "quick_actions": "ਤੁਰੰਤ ਕਰਵਾਈ",
        "approve_leave": "ਛੁੱਟੀ ਮਨਜ਼ੂਰ ਕਰੋ",
        "transfers": "ਤਬਾਦਲੇ",
        "team_reports": "ਟੀਮ ਰਿਪੋਰਟਾਂ",
        "announce": "ਐਲਾਨ ਕਰੋ",
        "mark_in": "ਹਾਜ਼ਰੀ ਲਗਾਓ (ਚਿਹਰਾ)",
        "setup_face": "ਚਿਹਰਾ ਸੈੱਟਅੱਪ",
        "apply_leave": "ਛੁੱਟੀ ਲਈ ਅਰਜ਼ੀ",
        "payslip": "ਤਨਖਾਹ ਪਰਚੀ",
        "form_16": "ਫਾਰਮ 16",
        "recent_transfers": "ਹਾਲੀਆ ਤਬਾਦਲੇ",
        "recent_payroll": "ਹਾਲੀਆ ਤਨਖਾਹ",
        "view_all": "ਸਾਰਾ ਇਤਿਹਾਸ ਵੇਖੋ",
        "active_grievances": "ਸਰਗਰਮ ਸ਼ਿਕਾਇਤਾਂ",
        "view_all_tickets": "ਸਾਰੀਆਂ ਟਿਕਟਾਂ ਵੇਖੋ",
        "logout": "ਲੌਗ ਆਉਟ",
        "need_help": "ਮਦਦ ਚਾਹੀਦੀ ਹੈ?",
        "contact_support": "ਸੰਪਰਕ ਕਰੋ",
        "nav_dashboard": "ਡੈਸ਼ਬੋਰਡ",
        "nav_attendance": "ਹਾਜ਼ਰੀ",
        "nav_payroll": "ਤਨਖਾਹ",
        "nav_transfers": "ਤਬਾਦਲੇ",
        "nav_grievances": "ਸ਼ਿਕਾਇਤਾਂ",
        "nav_profile": "ਪ੍ਰੋਫਾਈਲ",
        "wip": "ਕੰਮ ਜਾਰੀ ਹੈ",
        "grievance_submitted": "ਸ਼ਿਕਾਇਤ ਦਰਜ ਹੋ ਗਈ!",
        "grievance_title": "ਸਿਰਲੇਖ",
        "grievance_desc": "ਵੇਰਵਾ",
        "submit": "ਜਮ੍ਹਾਂ ਕਰੋ",
        "cancel": "ਰੱਦ ਕਰੋ",
        "submit_grievance_modal_title": "ਸ਼ਿਕਾਇਤ ਦਰਜ ਕਰੋ",

        "access_denied": "ਪਹੁੰਚ ਅਸਵੀਕਾਰ",
        "tracking_presence": "ਮਾਸਿਕ ਹਾਜ਼ਰੀ ਟਰੈਕਿੰਗ",
        "search_employee": "ਕਰਮਚਾਰੀ ਖੋਜੋ...",
        "loading_attendance": "ਹਾਜ਼ਰੀ ਡਾਟਾ ਲੋਡ ਹੋ ਰਿਹਾ ਹੈ...",
        "present_days": "ਹਾਜ਼ਰ",
        "absent_off": "ਗੈਰਹਾਜ਼ਰ/ਛੁੱਟੀ",
        "total_days": "ਕੁੱਲ ਦਿਨ",
        "no_records": "ਕੋਈ ਰਿਕਾਰਡ ਨਹੀਂ ਮਿਲਿਆ।",
        "dept_documents": "ਵਿਭਾਗ ਦਸਤਾਵੇਜ਼",
        "dept_docs_desc": "ਆਪਣੇ ਵਿਭਾਗ ਦੇ ਸਾਰੇ ਸਰਕਾਰੀ ਦਸਤਾਵੇਜ਼ਾਂ ਤੱਕ ਪਹੁੰਚ ਅਤੇ ਪ੍ਰਬੰਧਨ ਕਰੋ।",
        "total_docs": "ਕੁੱਲ ਦਸਤਾਵੇਜ਼",
        "doc_name": "ਦਸਤਾਵੇਜ਼ ਦਾ ਨਾਮ",
        "doc_date": "ਮਿਤੀ",
        "doc_type": "ਕਿਸਮ",
        "doc_actions": "ਕਾਰਵਾਈ",
        "print_doc": "ਦਸਤਾਵੇਜ਼ ਪ੍ਰਿੰਟ ਕਰੋ",
        "view_doc": "ਦਸਤਾਵੇਜ਼ ਵੇਖੋ",
        "viewing_doc": "ਤੁਸੀਂ ਵੇਖ ਰਹੇ ਹੋ",
        "doc_placeholder": "ਇਹ ਅਸਲ ਦਸਤਾਵੇਜ਼ ਦਰਸ਼ਕ ਲਈ ਇੱਕ ਥਾਂ ਹੈ।",
        "print": "ਪ੍ਰਿੰਟ",
        "download": "ਡਾਊਨਲੋਡ",
        "dept_grievances": "ਵਿਭਾਗ ਦੀਆਂ ਸ਼ਿਕਾਇਤਾਂ",
        "dept_grievances_desc": "ਆਪਣੇ ਵਿਭਾਗ ਦੀਆਂ ਸ਼ਿਕਾਇਤਾਂ ਦੀ ਸਮੀਖਿਆ ਕਰੋ ਅਤੇ ਹੱਲ ਕਰੋ",
        "resolve_fail": "ਸ਼ਿਕਾਇਤ ਹੱਲ ਕਰਨ ਵਿੱਚ ਅਸਫਲ।",
        "reply_fail": "ਜਵਾਬ ਭੇਜਣ ਵਿੱਚ ਅਸਫਲ",
        "dept_workforce": "ਵਿਭਾਗ ਕਾਰਜਬਲ",
        "managing_workers": "ਕਾਰਜਬਲ ਪ੍ਰਬੰਧਨ",
        "search_workers": "ਕਰਮਚਾਰੀ ਖੋਜੋ...",
        "loading_workforce": "ਕਾਰਜਬਲ ਡਾਟਾ ਲੋਡ ਹੋ ਰਿਹਾ ਹੈ...",
        "employee_header": "ਕਰਮਚਾਰੀ",
        "post_designation": "ਅਹੁਦਾ",
        "contact_header": "ਸੰਪਰਕ",
        "status_header": "ਸਥਿਤੀ",
        "face_reg": "ਚਿਹਰਾ ਰਜਿ.",
        "pending_face": "ਬਾਕੀ ਚਿਹਰਾ",
        "onboarded": "ਆਨਬੋਰਡ",
        "new_status": "ਨਵਾਂ",
        "attendance_history": "ਹਾਜ਼ਰੀ ਇਤਿਹਾਸ",
        "viewing_records": "ਆਈਡੀ ਲਈ ਰਿਕਾਰਡ ਵੇਖ ਰਹੇ ਹਾਂ:",
        "recent_activity": "ਹਾਲੀਆ ਗਤੀਵਿਧੀ",
        "detailed_records": "ਵਿਸਤ੍ਰਿਤ ਰਿਕਾਰਡ",
        "time_header": "ਸਮਾਂ",
        "location_header": "ਸ਼ਹਿਰ",
        "attendance_analytics_hub": "ਹਾਜ਼ਰੀ ਵਿਸ਼ਲੇਸ਼ਣ",
        "real_time_presence": "ਵਿਭਾਗਾਂ ਵਿੱਚ ਰੀਅਲ-ਟਾਈਮ ਹਾਜ਼ਰੀ",
        "payroll_command_center": "ਤਨਖਾਹ ਕਮਾਂਡ ਸੈਂਟਰ",
        "cycle_txt": "ਚੱਕਰ",
        "cycle_completed": "ਚੱਕਰ ਪੂਰਾ ਹੋਇਆ",
        "action_required_caps": "ਕਾਰਵਾਈ ਲੋੜੀਂਦੀ",
        "total_allocated": "ਕੁੱਲ ਵੰਡਿਆ",
        "actual_disbursal": "ਅਸਲ ਵੰਡ",
        "release_batch_payout": "ਬੈਚ ਭੁਗਤਾਨ ਜਾਰੀ ਕਰੋ",
        "payouts_released": "ਭੁਗਤਾਨ ਜਾਰੀ ਕੀਤੇ ਗਏ",
        "budget_status": "ਬਜਟ ਸਥਿਤੀ",
        "active_grievances_label": "ਸਰਗਰਮ ਸ਼ਿਕਾਇਤਾਂ",
        "present_days_chart": "ਹਾਜ਼ਰ ਦਿਨ",
        "tab_overview": "ਝਲਕ",
        "tab_payroll": "ਤਨਖਾਹ",
        "tab_grievances": "ਸ਼ਿਕਾਇਤਾਂ",
        "tab_leaves": "ਛੁੱਟੀਆਂ",
        "tab_livemap": "ਲਾਈਵ ਨਕਸ਼ਾ",
        "status_processing": "ਕਾਰਵਾਈ ਜਾਰੀ",
        "status_pending": "ਬਕਾਇਆ",
        "status_released": "ਜਾਰੀ ਕੀਤਾ",
        "legend_present": "ਹਾਜ਼ਰ",
        "legend_absent": "ਗੈਰਹਾਜ਼ਰ",
        "legend_on_leave": "ਛੁੱਟੀ 'ਤੇ",
        "dept_education": "ਸਿੱਖਿਆ",
        "dept_health": "ਸਿਹਤ",
        "dept_engineering": "ਇੰਜੀਨੀਅਰਿੰਗ",
        "dept_sanitation": "ਸਫਾਈ",
        "dept_general": "ਆਮ",

        "service_request": "ਸੇਵਾ ਬੇਨਤੀ",
        "id_card_generator": "ਆਈਡੀ ਕਾਰਡ ਜਨਰੇਟਰ",
        "dept_document_nav": "ਵਿਭਾਗ ਦਸਤਾਵੇਜ਼",
        "department_suffix": "ਵਿਭਾਗ",
        "doc_type_transfer_order": "ਤਬਾਦਲੇ ਦੇ ਆਦੇਸ਼",
        "doc_type_general": "ਆਮ",
        "doc_type_official": "ਦਫ਼ਤਰੀ",

        "grievance_hub": "ਸ਼ਿਕਾਇਤ ਕੇਂਦਰ",
        "grievance_hub_desc": "ਸ਼ਿਕਾਇਤਾਂ ਦੀ ਸਮੀਖਿਆ ਅਤੇ ਹੱਲ ਕਰੋ",
        "filter_all": "ਸਾਰੇ",
        "filter_officials": "ਅਧਿਕਾਰੀ",
        "filter_workers": "ਕਰਮਚਾਰੀ",
        "grievance_resolved": "ਹੱਲ ਹੋਇਆ",
        "grievance_pending": "ਬਕਾਇਆ",
        "grievance_active_count": "ਸਰਗਰਮ",

        "management_actions": "ਪ੍ਰਬੰਧਨ ਕਾਰਵਾਈਆਂ",
        "team_reports_label": "ਟੀਮ ਰਿਪੋਰਟਾਂ",
        "department_notices": "ਵਿਭਾਗ ਨੋਟਿਸ",
        "manage_notices": "ਨੋਟਿਸ ਪ੍ਰਬੰਧਿਤ ਕਰੋ",
        "notices_posted_text": "ਤੁਸੀਂ ਇਸ ਮਹੀਨੇ {count} ਨੋਟਿਸ ਪੋਸਟ ਕੀਤੇ ਹਨ।",
    },
    mr: {
        "dashboard_title_official": "अधिकारी डॅशबोर्ड",
        "dashboard_title_worker": "कामगार डॅशबोर्ड",
        "welcome_back": "स्वागत आहे",
        "what_happening": "आज तुमच्या खात्यात काय घडत आहे ते पहा.",
        "reports": "अहवाल",

        "team_attendance": "टीम उपस्थिती",
        "attendance_overview": "उपस्थिती आढावा",
        "view_report": "अहवाल पहा",
        "quick_actions": "त्वरित क्रिया",
        "approve_leave": "रजा मंजूर करा",
        "transfers": "बदल्या",
        "team_reports": "टीम अहवाल",
        "announce": "घोषणा करा",
        "mark_in": "हजेरी लावा (चेहरा)",
        "setup_face": "फेस आयडी सेट करा",
        "apply_leave": "रजेसाठी अर्ज करा",
        "payslip": "पगार स्लिप",
        "form_16": "फॉर्म 16",
        "recent_transfers": "अलीकडील बदल्या",
        "recent_payroll": "अलीकडील पगार",
        "view_all": "सर्व इतिहास पहा",
        "active_grievances": "सक्रिय तक्रारी",
        "view_all_tickets": "सर्व तिकिटे पहा",
        "logout": "लॉग आउट",
        "need_help": "मदत हवी आहे?",
        "contact_support": "संपर्क साधा",
        "nav_dashboard": "डॅशबोर्ड",
        "nav_attendance": "उपस्थिती",
        "nav_payroll": "पगार",
        "nav_transfers": "बदल्या",
        "nav_grievances": "तक्रारी",
        "nav_profile": "प्रोफाइल",
        "wip": "काम चालू आहे",
        "grievance_submitted": "तक्रार यशस्वीरित्या नोंदवली गेली!",
        "grievance_title": "शीर्षक",
        "grievance_desc": "वर्णन",
        "submit": "सबमिट करा",
        "cancel": "रद्द करा",
        "submit_grievance_modal_title": "तक्रार नोंदवा",

        "access_denied": "प्रवेश नाकारला",
        "tracking_presence": "मासिक उपस्थिती ट्रॅकिंग",
        "search_employee": "कर्मचारी शोधा...",
        "loading_attendance": "उपस्थिती डेटा लोड होत आहे...",
        "present_days": "उपस्थित",
        "absent_off": "अनुपस्थित/सुट्टी",
        "total_days": "एकूण दिवस",
        "no_records": "कोणतेही रेकॉर्ड सापडले नाहीत.",
        "dept_documents": "विभाग दस्तऐवज",
        "dept_docs_desc": "आपल्या विभागातील सर्व अधिकृत कागदपत्रे ऍक्सेस आणि व्यवस्थापित करा.",
        "total_docs": "एकूण दस्तऐवज",
        "doc_name": "दस्तऐवजाचे नाव",
        "doc_date": "तारीख",
        "doc_type": "प्रकार",
        "doc_actions": "क्रिया",
        "print_doc": "दस्तऐवज प्रिंट करा",
        "view_doc": "दस्तऐवज पहा",
        "viewing_doc": "तुम्ही पाहत आहात",
        "doc_placeholder": "हा वास्तविक दस्तऐवज दर्शविण्यासाठी एक प्लेसहोल्डर आहे.",
        "print": "प्रिंट",
        "download": "डाउनलोड",
        "dept_grievances": "विभाग तक्रारी",
        "dept_grievances_desc": "आपल्या विभागातील तक्रारींचे पुनरावलोकन करा आणि निराकरण करा",
        "resolve_fail": "तक्रार सोडवण्यात अयशस्वी.",
        "reply_fail": "उत्तर पाठवण्यात अयशस्वी",
        "dept_workforce": "विभाग कर्मचारी",
        "managing_workers": "कर्मचारी व्यवस्थापन",
        "search_workers": "कामगार शोधा...",
        "loading_workforce": "कर्मचारी डेटा लोड होत आहे...",
        "employee_header": "कर्मचारी",
        "post_designation": "पद",
        "contact_header": "संपर्क",
        "status_header": "स्थिती",
        "face_reg": "फेसReg",
        "pending_face": "पेंडिंग फेस",
        "onboarded": "ऑनबोर्डेड",
        "new_status": "नवीन",
        "attendance_history": "उपस्थिती इतिहास",
        "viewing_records": "आयडीचे रेकॉर्ड पाहत आहे:",
        "recent_activity": "अलीकडील क्रियाकलाप",
        "detailed_records": "तपशीलवार रेकॉर्ड",
        "time_header": "वेळ",
        "location_header": "स्थान",
        "attendance_analytics_hub": "उपस्थिती विश्लेषण केंद्र",
        "real_time_presence": "विभागांमधील रिअल-टाइम उपस्थिती",
        "payroll_command_center": "पगार कमांड सेंटर",
        "cycle_txt": "चक्र",
        "cycle_completed": "चक्र पूर्ण",
        "action_required_caps": "कृती आवश्यक",
        "total_allocated": "एकूण वाटप",
        "actual_disbursal": "प्रत्यक्ष वितरण",
        "release_batch_payout": "बॅच पेआउट जारी करा",
        "payouts_released": "पेआउट जारी",
        "budget_status": "बजेट स्थिती",
        "active_grievances_label": "सक्रिय तक्रारी",
        "present_days_chart": "उपस्थित दिवस",
        "tab_overview": "आढावा",
        "tab_payroll": "पगार",
        "tab_grievances": "तक्रारी",
        "tab_leaves": "सुट्ट्या",
        "tab_livemap": "लाइव्ह नकाशा",
        "status_processing": "प्रक्रियेत",
        "status_pending": "प्रलंबित",
        "status_released": "जारी",
        "legend_present": "उपस्थित",
        "legend_absent": "अनुपस्थित",
        "legend_on_leave": "रजेवर",
        "dept_education": "शिक्षण",
        "dept_health": "आरोग्य",
        "dept_engineering": "अभियांत्रिकी",
        "dept_sanitation": "स्वच्छता",
        "dept_general": "सामान्य",

        "service_request": "सेवा विनंती",
        "id_card_generator": "आयडी कार्ड जनरेटर",
        "dept_document_nav": "विभाग दस्तऐवज",
        "department_suffix": "विभाग",
        "doc_type_transfer_order": "बदली आदेश",
        "doc_type_general": "सामान्य",
        "doc_type_official": "अधिकृत",

        "grievance_hub": "तक्रार केंद्र",
        "grievance_hub_desc": "तक्रारींचे पुनरावलोकन आणि निराकरण करा",
        "filter_all": "सर्व",
        "filter_officials": "अधिकारी",
        "filter_workers": "कर्मचारी",
        "grievance_resolved": "निराकरण झाले",
        "grievance_pending": "प्रलंबित",
        "grievance_active_count": "सक्रिय",

        "management_actions": "व्यवस्थापन क्रिया",
        "team_reports_label": "टीम अहवाल",
        "department_notices": "विभाग सूचना",
        "manage_notices": "सूचना व्यवस्थापित करा",
        "notices_posted_text": "तुम्ही या महिन्यात {count} सूचना पोस्ट केल्या आहेत.",
    },
    ta: {
        "dashboard_title_official": "அதிகாரி டாஷ்போர்டு",
        "dashboard_title_worker": "தொழிலாளர் டாஷ்போர்டு",
        "welcome_back": "மீண்டும் வருக",
        "what_happening": "இன்று உங்கள் கணக்கில் என்ன நடக்கிறது என்று பாருங்கள்.",
        "reports": "அறிக்கைகள்",

        "team_attendance": "குழு வருகை",
        "attendance_overview": "வருகை கண்ணோட்டம்",
        "view_report": "அறிக்கையை பார்க்கவும்",
        "quick_actions": "விரைவு செயல்கள்",
        "approve_leave": "விடுப்பை அங்கீகரிக்கவும்",
        "transfers": "இடமாற்றங்கள்",
        "team_reports": "குழு அறிக்கைகள்",
        "announce": "அறிவிப்பு",
        "mark_in": "வருகையை பதிவு செய் (முகம்)",
        "setup_face": "முக ஐடியை அமைக்கவும்",
        "apply_leave": "விடுப்பு விண்ணப்பிக்கவும்",
        "payslip": "சம்பள சீட்டு",
        "form_16": "படிவம் 16",
        "recent_transfers": "சமீபத்திய இடமாற்றங்கள்",
        "recent_payroll": "சமீபத்திய சம்பளம்",
        "view_all": "எல்லா வரலாற்றையும் காண்க",
        "active_grievances": "செயலில் உள்ள குறைகள்",
        "view_all_tickets": "அனைத்து டிக்கெட்டுகளையும் காண்க",
        "logout": "வெளியேறு",
        "need_help": "உதவி தேவையா?",
        "contact_support": "தொடர்பு கொள்ளவும்",
        "nav_dashboard": "டாஷ்போர்டு",
        "nav_attendance": "வருகை",
        "nav_payroll": "சம்பளம்",
        "nav_transfers": "இடமாற்றங்கள்",
        "nav_grievances": "குறைகள்",
        "nav_profile": "சுயவிவரம்",
        "wip": "பணி நடந்து கொண்டிருக்கிறது",
        "grievance_submitted": "குறை வெற்றிகரமாக சமர்ப்பிக்கப்பட்டது!",
        "grievance_title": "தலைப்பு",
        "grievance_desc": "விளக்கம்",
        "submit": "சமர்ப்பிக்கவும்",
        "cancel": "ரத்துசெய்",
        "submit_grievance_modal_title": "குறை சமர்ப்பிக்கவும்",

        "access_denied": "அனுமதி மறுக்கப்பட்டது",
        "tracking_presence": "மாதாந்திர வருகை கண்காணிப்பு",
        "search_employee": "ஊழியரைத் தேடுங்கள்...",
        "loading_attendance": "வருகை தரவு ஏற்றப்படுகிறது...",
        "present_days": "வருகை",
        "absent_off": "வரவில்லை/விடுப்பு",
        "total_days": "மொத்த நாட்கள்",
        "no_records": "பதிவுகள் எதுவும் இல்லை.",
        "dept_documents": "துறை ஆவணங்கள்",
        "dept_docs_desc": "உங்கள் துறையின் அனைத்து அதிகாரப்பூர்வ ஆவணங்களையும் அணுகவும் மற்றும் நிர்வகிக்கவும்.",
        "total_docs": "மொத்த ஆவணங்கள்",
        "doc_name": "ஆவணத்தின் பெயர்",
        "doc_date": "தேதி",
        "doc_type": "வகை",
        "doc_actions": "செயல்கள்",
        "print_doc": "ஆவணத்தை அச்சிடுக",
        "view_doc": "ஆவணத்தைப் பார்க்கவும்",
        "viewing_doc": "நீங்கள் பார்க்கிறீர்கள்",
        "doc_placeholder": "இது உண்மையான ஆவணப் பார்வைக்கான ஒரு ஒதுக்கிடமாகும்.",
        "print": "அச்சிடு",
        "download": "பதிவிறக்கவும்",
        "dept_grievances": "துறை குறைகள்",
        "dept_grievances_desc": "உங்கள் துறையின் குறைகளை மதிப்பாய்வு செய்து தீர்க்கவும்",
        "resolve_fail": "குறையைத் தீர்க்க முடியவில்லை.",
        "reply_fail": "பதில் அனுப்ப முடியவில்லை",
        "dept_workforce": "துறை பணியாளர்கள்",
        "managing_workers": "பணியாளர் மேலாண்மை",
        "search_workers": "தொழிலாளர்களைத் தேடுங்கள்...",
        "loading_workforce": "பணியாளர் தரவு ஏற்றப்படுகிறது...",
        "employee_header": "ஊழியர்",
        "post_designation": "பதவி",
        "contact_header": "தொடர்பு",
        "status_header": "நிலை",
        "face_reg": "முகம் பதிவு",
        "pending_face": "முகம் நிலுவையில்",
        "onboarded": "சேர்க்கப்பட்டது",
        "new_status": "புதியது",
        "attendance_history": "வருகை வரலாறு",
        "viewing_records": "பதிவுகளைப் பார்க்கிறது:",
        "recent_activity": "சமீபத்திய செயல்பாடு",
        "detailed_records": "விரிவான பதிவுகள்",
        "time_header": "நேரம்",
        "location_header": "இடம்",
        "attendance_analytics_hub": "வருகை பகுப்பாய்வு மையம்",
        "real_time_presence": "துறைகள் முழுவதும் நிகழ்நேர வருகை",
        "payroll_command_center": "சம்பளக் கட்டுப்பாட்டு மையம்",
        "cycle_txt": "சுழற்சி",
        "cycle_completed": "சுழற்சி முடிந்தது",
        "action_required_caps": "நடவடிக்கை தேவை",
        "total_allocated": "மொத்தம் ஒதுக்கப்பட்டது",
        "actual_disbursal": "உண்மையான பட்டுவாடா",
        "release_batch_payout": "தொகுதி கட்டணம் வெளியிடு",
        "payouts_released": "கட்டணம் வெளியிடப்பட்டது",
        "budget_status": "பட்ஜெட் நிலை",
        "active_grievances_label": "செயலில் உள்ள குறைகள்",
        "present_days_chart": "வருகை நாட்கள்",
        "tab_overview": "கண்ணோட்டம்",
        "tab_payroll": "சம்பளம்",
        "tab_grievances": "குறைகள்",
        "tab_leaves": "விடுப்புகள்",
        "tab_livemap": "நேரடி வரைபடம்",
        "status_processing": "செயலாக்கம்",
        "status_pending": "நிலுவையில்",
        "status_released": "வெளியிடப்பட்டது",
        "legend_present": "வருகை",
        "legend_absent": "வராதவர்",
        "legend_on_leave": "விடுப்பில்",
        "dept_education": "கல்வி",
        "dept_health": "சுகாதாரம்",
        "dept_engineering": "பொறியியல்",
        "dept_sanitation": "துப்புரவு",
        "dept_general": "பொது",

        "service_request": "சேவை கோரிக்கை",
        "id_card_generator": "அடையாள அட்டை உருவாக்கி",
        "dept_document_nav": "துறை ஆவணம்",
        "department_suffix": "துறை",
        "doc_type_transfer_order": "இடமாற்ற ஆணை",
        "doc_type_general": "பொது",
        "doc_type_official": "அதிகாரப்பூர்வ",

        "grievance_hub": "குறை மையம்",
        "grievance_hub_desc": "குறைகளை மதிப்பாய்வு செய்து தீர்க்கவும்",
        "filter_all": "அனைத்தும்",
        "filter_officials": "அதிகாரிகள்",
        "filter_workers": "பணியாளர்கள்",
        "grievance_resolved": "தீர்க்கப்பட்டது",
        "grievance_pending": "நிலுவையில்",
        "grievance_active_count": "செயலில்",

        "management_actions": "நிர்வாக நடவடிக்கைகள்",
        "team_reports_label": "குழு அறிக்கைகள்",
        "department_notices": "துறை அறிவிப்புகள்",
        "manage_notices": "அறிவிப்புகளை நிர்வகிக்கவும்",
        "notices_posted_text": "இந்த மாதம் நீங்கள் {count} அறிவிப்புகளை இடுகையிட்டுள்ளீர்கள்.",
    },
    te: {
        "dashboard_title_official": "అధికారి డాష్‌బోర్డ్",
        "dashboard_title_worker": "కార్మికుడు డాష్‌బోర్డ్",
        "welcome_back": "స్వాగతం",
        "what_happening": "ఈ రోజు మీ ఖాతాలో ఏం జరుగుతుందో చూడండి.",
        "reports": "నివేదికలు",

        "team_attendance": "జట్టు హాజరు",
        "attendance_overview": "హాజరు అవలోకనం",
        "view_report": "నివేదిక చూడండి",
        "quick_actions": "త్వరిత చర్యలు",
        "approve_leave": "సెలవు ఆమోదించండి",
        "transfers": "బదిలీలు",
        "team_reports": "జట్టు నివేదికలు",
        "announce": "ప్రకటించండి",
        "mark_in": "హాజరు వేయండి (ముఖం)",
        "setup_face": "ఫేస్ ఐడి సెట్ చేయండి",
        "apply_leave": "సెలవు దరఖాస్తు",
        "payslip": "జీతం స్లిప్",
        "form_16": "ఫారం 16",
        "recent_transfers": "ఇటీవలి బదిలీలు",
        "recent_payroll": "ఇటీవలి జీతం",
        "view_all": "మొత్తం చరిత్ర చూడండి",
        "active_grievances": "యాక్టివ్ ఫిర్యాదులు",
        "view_all_tickets": "అన్ని టిక్కెట్లు చూడండి",
        "logout": "లాగ్ అవుట్",
        "need_help": "సహాయం కావాలా?",
        "contact_support": "సంప్రదించండి",
        "nav_dashboard": "డాష్‌బోర్డ్",
        "nav_attendance": "హాజరు",
        "nav_payroll": "జీతం",
        "nav_transfers": "బదిలీలు",
        "nav_grievances": "ఫిర్యాదులు",
        "nav_profile": "ప్రొఫైల్",
        "wip": "పని జరుగుతోంది",
        "grievance_submitted": "ఫిర్యాదు విజయవంతంగా సమర్పించబడింది!",
        "grievance_title": "శీర్షిక",
        "grievance_desc": "వివరణ",
        "submit": "సమర్పించు",
        "cancel": "రద్దు చేయండి",
        "submit_grievance_modal_title": "ఫిర్యాదు చేయండి",

        "access_denied": "యాక్సెస్ నిరాకరించబడింది",
        "tracking_presence": "నెలవారీ హాజరు ట్రాకింగ్",
        "search_employee": "ఉద్యోగిని వెతకండి...",
        "loading_attendance": "హాజరు డేటా లోడ్ అవుతోంది...",
        "present_days": "హాజరు",
        "absent_off": "గైర్హాజరు/సెలవు",
        "total_days": "మొత్తం రోజులు",
        "no_records": "రికార్డులు ఏవీ కనుగొనబడలేదు.",
        "dept_documents": "శాఖ పత్రాలు",
        "dept_docs_desc": "మీ శాఖ యొక్క అన్ని అధికారిక పత్రాలను యాక్సెస్ చేయండి మరియు నిర్వహించండి.",
        "total_docs": "మొత్తం పత్రాలు",
        "doc_name": "పత్రం పేరు",
        "doc_date": "తేదీ",
        "doc_type": "రకం",
        "doc_actions": "చర్యలు",
        "print_doc": "పత్రాన్ని ముద్రించండి",
        "view_doc": "పత్రాన్ని వీక్షించండి",
        "viewing_doc": "మీరు వీక్షిస్తున్నారు",
        "doc_placeholder": "ఇది వాస్తవ పత్ర వీక్షకుడికి ప్లేస్‌హోల్డర్.",
        "print": "ముద్రించు",
        "download": "డౌన్‌లోడ్",
        "dept_grievances": "శాఖ ఫిర్యాదులు",
        "dept_grievances_desc": "మీ శాఖ నుండి వచ్చిన ఫిర్యాదులను సమీక్షించండి మరియు పరిష్కరించండి",
        "resolve_fail": "ఫిర్యాదును పరిష్కరించడంలో విఫలమైంది.",
        "reply_fail": "సమాధానం పంపడంలో విఫలమైంది",
        "dept_workforce": "శాఖ సిబ్బంది",
        "managing_workers": "సిబ్బంది నిర్వహణ",
        "search_workers": "కార్మికులను వెతకండి...",
        "loading_workforce": "సిబ్బంది డేటా లోడ్ అవుతోంది...",
        "employee_header": "ఉద్యోగి",
        "post_designation": "పదవి",
        "contact_header": "సంప్రదించండి",
        "status_header": "స్థితి",
        "face_reg": "ఫేస్ రెగ్",
        "pending_face": "పెండింగ్ ఫేస్",
        "onboarded": "ఆన్‌బోర్డ్ చేయబడింది",
        "new_status": "కొత్తది",
        "attendance_history": "హాజరు చరిత్ర",
        "viewing_records": "ఐడి రికార్డులు చూస్తున్నారు:",
        "recent_activity": "ఇటీవలి కార్యాచరణ",
        "detailed_records": "వివరణాత్మక రికార్డులు",
        "time_header": "సమయం",
        "location_header": "స్థానము",
        "attendance_analytics_hub": "హాజరు విశ్లేషణ కేంద్రం",
        "real_time_presence": "విభాగాలలో రియల్ టైమ్ హాజరు",
        "payroll_command_center": "పేరోల్ కమాండ్ సెంటర్",
        "cycle_txt": "సైకిల్",
        "cycle_completed": "సైకిల్ పూర్తయింది",
        "action_required_caps": "చర్య అవసరం",
        "total_allocated": "మొత్తం కేటాయించినది",
        "actual_disbursal": "వాస్తవ పంపిణీ",
        "release_batch_payout": "బ్యాచ్ చెల్లింపు విడుదల",
        "payouts_released": "చెల్లింపులు విడుదలయ్యాయి",
        "budget_status": "బడ్జెట్ స్థితి",
        "active_grievances_label": "యాక్టివ్ ఫిర్యాదులు",
        "present_days_chart": "హాజరైన రోజులు",
        "tab_overview": "అవలోకనం",
        "tab_payroll": "జీతం",
        "tab_grievances": "ఫిర్యాదులు",
        "tab_leaves": "సెలవులు",
        "tab_livemap": "లైవ్ మ్యాప్",
        "status_processing": "ప్రాసెసింగ్",
        "status_pending": "పెండింగ్",
        "status_released": "విడుదల",
        "legend_present": "హాజరు",
        "legend_absent": "గైర్హాజరు",
        "legend_on_leave": "సెలవులో",
        "dept_education": "విద్య",
        "dept_health": "ఆరోగ్యం",
        "dept_engineering": "ఇంజనీరింగ్",
        "dept_sanitation": "పారిశుధ్యం",
        "dept_general": "సాధారణ",

        "service_request": "సేవా అభ్యర్థన",
        "id_card_generator": "ID కార్డ్ జనరేటర్",
        "dept_document_nav": "శాఖ పత్రాలు",
        "department_suffix": "శాఖ",
        "doc_type_transfer_order": "బదిలీ ఉత్తర్వు",
        "doc_type_general": "సాధారణ",
        "doc_type_official": "అధికారిక",

        "grievance_hub": "ఫిర్యాదు కేంద్రం",
        "grievance_hub_desc": "సమస్యలను సమీక్షించండి మరియు పరిష్కరించండి",
        "filter_all": "అన్నీ",
        "filter_officials": "అధికారులు",
        "filter_workers": "కార్మికులు",
        "grievance_resolved": "పరిష్కరించబడింది",
        "grievance_pending": "పెండింగ్‌లో ఉంది",
        "grievance_active_count": "యాక్టివ్",

        "management_actions": "నిర్వహణ చర్యలు",
        "team_reports_label": "జట్టు నివేదికలు",
        "department_notices": "శాఖ నోటీసులు",
        "manage_notices": "నోటీసులను నిర్వహించండి",
        "notices_posted_text": "మీరు ఈ నెలలో {count} నోటీసులను పోస్ట్ చేశారు.",
    },
    bn: {
        "dashboard_title_official": "অফিসিয়াল ড্যাশবোর্ড",
        "dashboard_title_worker": "কর্মী ড্যাশবোর্ড",
        "welcome_back": "স্বাগতম",
        "what_happening": "আজ আপনার অ্যাকাউন্টে কী ঘটছে তা দেখুন।",
        "reports": "রিপোর্ট",

        "team_attendance": "টিম উপস্থিতি",
        "attendance_overview": "উপস্থিতি ওভারভিউ",
        "view_report": "রিপোর্ট দেখুন",
        "quick_actions": "দ্রুত পদক্ষেপ",
        "approve_leave": "ছুটি অনুমোদন করুন",
        "transfers": "বদলি",
        "team_reports": "টিম রিপোর্ট",
        "announce": "ঘোষণা করুন",
        "mark_in": "হাজিরা দিন (মুখ)",
        "setup_face": "ফেস আইডি সেট করুন",
        "apply_leave": "ছুটির আবেদন",
        "payslip": "বেতন স্লিপ",
        "form_16": "ফর্ম 16",
        "recent_transfers": "সাম্প্রতিক বদলি",
        "recent_payroll": "সাম্প্রতিক বেতন",
        "view_all": "সব ইতিহাস দেখুন",
        "active_grievances": "সক্রিয় অভিযোগ",
        "view_all_tickets": "সব টিকেট দেখুন",
        "logout": "লগ আউট",
        "need_help": "সাহায্য প্রয়োজন?",
        "contact_support": "যোগাযোগ করুন",
        "nav_dashboard": "ড্যাশবোর্ড",
        "nav_attendance": "উপস্থিতি",
        "nav_payroll": "বেতন",
        "nav_transfers": "বদলি",
        "nav_grievances": "অভিযোগ",
        "nav_profile": "প্রোফাইল",
        "wip": "কাজ চলছে",
        "grievance_submitted": "অভিযোগ সফলভাবে জমা দেওয়া হয়েছে!",
        "grievance_title": "শিরোনাম",
        "grievance_desc": "বিবরণ",
        "submit": "জমা দিন",
        "cancel": "বাতিল",
        "submit_grievance_modal_title": "অভিযোগ জমা দিন",

        "access_denied": "প্রবেশাধিকার অস্বীকৃত",
        "tracking_presence": "মাসিক উপস্থিতি ট্র্যাকিং",
        "search_employee": "কর্মী খুঁজুন...",
        "loading_attendance": "উপস্থিতি তথ্য লোড হচ্ছে...",
        "present_days": "উপস্থিত",
        "absent_off": "অনুপস্থিত/ছুটি",
        "total_days": "মোট দিন",
        "no_records": "কোন রেকর্ড পাওয়া যায়নি।",
        "dept_documents": "বিভাগীয় নথি",
        "dept_docs_desc": "আপনার বিভাগের সমস্ত অফিসিয়াল নথি অ্যাক্সেস এবং পরিচালনা করুন।",
        "total_docs": "মোট নথি",
        "doc_name": "নথির নাম",
        "doc_date": "তারিখ",
        "doc_type": "ধরন",
        "doc_actions": "পদক্ষেপ",
        "print_doc": "নথি প্রিন্ট করুন",
        "view_doc": "নথি দেখুন",
        "viewing_doc": "আপনি দেখছেন",
        "doc_placeholder": "এটি আসল নথি ভিউয়ারের জন্য একটি স্থানধারক।",
        "print": "প্রিন্ট",
        "download": "ডাউনলোড",
        "dept_grievances": "বিভাগীয় অভিযোগ",
        "dept_grievances_desc": "আপনার বিভাগের অভিযোগগুলি পর্যালোচনা এবং সমাধান করুন",
        "resolve_fail": "অভিযোগ সমাধান করতে ব্যর্থ।",
        "reply_fail": "উত্তর পাঠাতে ব্যর্থ",
        "dept_workforce": "বিভাগীয় কর্মী",
        "managing_workers": "কর্মী ব্যবস্থাপনা",
        "search_workers": "শ্রমিক খুঁজুন...",
        "loading_workforce": "কর্মী তথ্য লোড হচ্ছে...",
        "employee_header": "কর্মচারী",
        "post_designation": "পদবী",
        "contact_header": "যোগাযোগ",
        "status_header": "অবস্থা",
        "face_reg": "ফেস রেজি",
        "pending_face": "ফেস বাকি",
        "onboarded": "অনবোর্ডেড",
        "new_status": "নতুন",
        "attendance_history": "উপস্থিতি ইতিহাস",
        "viewing_records": "আইডির জন্য রেকর্ড দেখা হচ্ছে:",
        "recent_activity": "সাম্প্রতিক কার্যকলাপ",
        "detailed_records": "বিস্তারিত রেকর্ড",
        "time_header": "সময়",
        "location_header": "অবস্থান",
        "attendance_analytics_hub": "উপস্থিতি বিশ্লেষণ কেন্দ্র",
        "real_time_presence": "বিভাগ জুড়ে রিয়েল-টাইম উপস্থিতি",
        "payroll_command_center": "বেতন কমান্ড সেন্টার",
        "cycle_txt": "চক্র",
        "cycle_completed": "চক্র সম্পন্ন",
        "action_required_caps": "পদক্ষেপ প্রয়োজন",
        "total_allocated": "মোট বরাদ্দ",
        "actual_disbursal": "প্রকৃত বিতরণ",
        "release_batch_payout": "ব্যাচ পেমেন্ট রিলিজ",
        "payouts_released": "পেমেন্ট রিলিজ করা হয়েছে",
        "budget_status": "বাজেটের অবস্থা",
        "active_grievances_label": "সক্রিয় অভিযোগ",
        "present_days_chart": "উপস্থিত দিন",
        "tab_overview": "একনজরে",
        "tab_payroll": "বেতন",
        "tab_grievances": "অভিযোগ",
        "tab_leaves": "ছুটি",
        "tab_livemap": "লাইভ ম্যাপ",
        "status_processing": "প্রক্রিয়াধীন",
        "status_pending": "অপেক্ষমাণ",
        "status_released": "রিলিজ",
        "legend_present": "উপস্থিত",
        "legend_absent": "অনুপস্থিত",
        "legend_on_leave": "ছুটিতে",
        "dept_education": "শিক্ষা",
        "dept_health": "স্বাস্থ্য",
        "dept_engineering": "ইঞ্জিনিয়ারিং",
        "dept_sanitation": "পরিচ্ছন্নতা",
        "dept_general": "সাধারণ",

        "service_request": "পরিষেবার অনুরোধ",
        "id_card_generator": "আইডি কার্ড জেনারেটর",
        "dept_document_nav": "বিভাগীয় নথি",
        "department_suffix": "বিভাগ",
        "doc_type_transfer_order": "বদলি আদেশ",
        "doc_type_general": "সাধারণ",
        "doc_type_official": "অফিসিয়াল",

        "grievance_hub": "অভিযোগ কেন্দ্র",
        "grievance_hub_desc": "সমস্যাগুলি পর্যালোচনা এবং সমাধান করুন",
        "filter_all": "সব",
        "filter_officials": "কর্মকর্তারা",
        "filter_workers": "কর্মীরা",
        "grievance_resolved": "সমাধান হয়েছে",
        "grievance_pending": "অপেক্ষমান",
        "grievance_active_count": "সক্রিয়",

        "management_actions": "ব্যবস্থাপনা কার্যক্রম",
        "team_reports_label": "টিম রিপোর্ট",
        "department_notices": "বিভাগীয় নোটিশ",
        "manage_notices": "নোটিশ পরিচালনা করুন",
        "notices_posted_text": "আপনি এই মাসে {count} টি নোটিশ পোস্ট করেছেন।",
    }
};

interface LanguageContextType {
    language: Language;
    setLanguage: (lang: Language) => void;
    t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
    const [language, setLanguage] = useState<Language>('en');

    const t = (key: string) => {
        return translations[language][key] || translations['en'][key] || key;
    };

    return (
        <LanguageContext.Provider value={{ language, setLanguage, t }}>
            {children}
        </LanguageContext.Provider>
    );
};

export const useLanguage = () => {
    const context = useContext(LanguageContext);
    if (!context) {
        throw new Error('useLanguage must be used within a LanguageProvider');
    }
    return context;
};

